### PR TITLE
fix: Remove Global Clutter

### PR DESCRIPTION
**Pull request by darthtrevino**
Tests currently depend on merging window properties into the global namespace. This fix minimizes that by only including navigator in the global namespace.  Other fixes include:

* Checking globals.XPathResult instead of expecting it to exist in the global NS.
* Testing against babel-generated code and tests, to ensure that the babel-runtime does not play a role in the test results.
* Correct react-addons-test-utils import to match how that's done in the latest version of React.
* Organization work in the NPM scripts.

### CODE REVIEW

**Comment by darthtrevino** [comment]
Hey @relekang ; @davija and I work together and we were plowing through a couple of issues that were causing tests to fail oddly. You can safely ignore his PR in favor of this one.

**Comment by relekang** [comment]
Oh, okay :)

Please follow the [angular commit guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#) (Sorry for not having the time to write a contributing guide).

Why have you changed mocha to run pretranspiled sources instead of letting mocha do the transpiling itself?

**Comment by davija** [comment]
I'm fine with this, it does fix my issue, however I believe leaving in the check for XPathResult in the global namespace isn't 100% correct.  It was only there due to the pre-test setup that copied everything from window into the global namespace.

**Comment by darthtrevino** [comment]
I can change the transpilation back if you prefer; my thinking was that I wanted to test the actual shipped artifact without the Babel runtime playing a role.

**Pull request closed without merging**
